module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Cinzel Decorative"', 'serif'],
        medieval: ['MedievalSharp', 'cursive'],
        body: ['"Crimson Text"', 'serif'],
      },
      colors: {
        parchment: '#f0d0b0',
        stone: {
          dark: '#1a1210',
          mid: '#2a2020',
          border: '#3d2d2d',
        },
        haven: {
          bg: '#1a2e1a',
          surface: '#2d4a2d',
          primary: '#7bc67b',
          accent: '#d4a843',
          border: '#3d6b3d',
          text: '#e8f0e8',
          muted: '#8fb88f',
        },
        wild: {
          bg: '#1a1a2e',
          surface: '#252547',
          primary: '#6b7fd4',
          accent: '#c7a84e',
          border: '#3a3a6b',
          text: '#d4d8f0',
          muted: '#7e84a8',
        },
        pass: {
          bg: '#1a1714',
          surface: '#2e2822',
          primary: '#d4953a',
          accent: '#e8c547',
          border: '#5c4a36',
          text: '#e8dcc8',
          muted: '#a89878',
        },
        marsh: {
          bg: '#0d0f0a',
          surface: '#1a1f14',
          primary: '#6b8c3a',
          accent: '#8b4513',
          border: '#3a4a2a',
          text: '#c8ccb8',
          muted: '#6b7060',
          eerie: '#4a7a5a',
        },
        throne: {
          bg: '#0a0000',
          surface: '#1a0a0a',
          primary: '#e84520',
          accent: '#ffb833',
          border: '#5a1a0a',
          text: '#f0d8c8',
          muted: '#8a6050',
          lava: '#ff6a00',
        },
      },
      animation: {
        'ember-rise': 'ember-rise var(--duration, 6s) ease-out infinite',
        'title-glow': 'title-glow 3s ease-in-out infinite alternate',
        'waypoint-pulse': 'waypoint-pulse 2s ease-in-out infinite',
        'fog-drift': 'fog-drift 20s linear infinite',
        'firefly-float': 'firefly-float var(--duration, 10s) ease-in-out infinite',
        'torch-flicker': 'torch-flicker 4s ease-in-out infinite',
        'wisp-drift': 'wisp-drift var(--duration, 8s) ease-in-out infinite',
        'dust-fall': 'dust-fall var(--duration, 15s) linear infinite',
        'fire-glow-pulse': 'fire-glow-pulse 4s ease-in-out infinite',
      },
      keyframes: {
        'ember-rise': {
          '0%': { transform: 'translateY(100vh) translateX(0) scale(0)', opacity: '0' },
          '10%': { opacity: '1', transform: 'translateY(90vh) translateX(var(--drift, 10px)) scale(1)' },
          '90%': { opacity: '0.6' },
          '100%': { transform: 'translateY(-10vh) translateX(var(--drift, -10px)) scale(0.3)', opacity: '0' },
        },
        'title-glow': {
          from: { textShadow: '0 0 10px rgba(255,106,0,0.5), 0 0 30px rgba(232,69,32,0.3), 0 0 60px rgba(139,26,0,0.2)' },
          to: { textShadow: '0 0 15px rgba(255,106,0,0.7), 0 0 40px rgba(232,69,32,0.4), 0 0 80px rgba(139,26,0,0.3)' },
        },
        'waypoint-pulse': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(var(--pulse-color, 232,69,32), 0.4)' },
          '50%': { boxShadow: '0 0 0 12px rgba(var(--pulse-color, 232,69,32), 0)' },
        },
        'fog-drift': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'firefly-float': {
          '0%, 100%': { transform: 'translateY(0) translateX(0)', opacity: '0.2' },
          '25%': { transform: 'translateY(var(--float-y, -30px)) translateX(var(--float-x, 15px))', opacity: '0.8' },
          '50%': { transform: 'translateY(var(--float-y2, -15px)) translateX(var(--float-x2, -10px))', opacity: '0.4' },
          '75%': { transform: 'translateY(var(--float-y3, -40px)) translateX(var(--float-x3, 20px))', opacity: '0.7' },
        },
        'torch-flicker': {
          '0%': { opacity: '0.8', transform: 'scale(1)' },
          '18%': { opacity: '1', transform: 'scale(1.02)' },
          '33%': { opacity: '0.85', transform: 'scale(0.99)' },
          '52%': { opacity: '0.95', transform: 'scale(1.01)' },
          '71%': { opacity: '0.88', transform: 'scale(1)' },
          '100%': { opacity: '0.8', transform: 'scale(1)' },
        },
        'wisp-drift': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)', opacity: '0.15' },
          '33%': { transform: 'translate(var(--wisp-x, 30px), var(--wisp-y, -20px)) scale(1.2)', opacity: '0.5' },
          '66%': { transform: 'translate(var(--wisp-x2, -20px), var(--wisp-y2, 10px)) scale(0.8)', opacity: '0.25' },
        },
        'dust-fall': {
          '0%': { transform: 'translateY(-10vh) translateX(0)', opacity: '0' },
          '10%': { opacity: '0.15' },
          '90%': { opacity: '0.1' },
          '100%': { transform: 'translateY(100vh) translateX(var(--drift, 20px))', opacity: '0' },
        },
        'fire-glow-pulse': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '0.9' },
        },
      },
    },
  },
  plugins: [],
};
